### ISSUE TITLE
Migration to 11.0

### ISSUE THREAD

**Issue by ddufresne** [modoolar/project_agile#1]
Hello Modoolar,

do you intend to port project_agile to Odoo version 11.0 ?
If so, what is your schedule ?

Thanks

**Comment by pnajman-modoolar** [comment]
Hi David,

Yes, we are working on v11 migration and our target is end of January.
Thanks for taking interest in this project and please stay tuned :)

Cheers,
Petar

**Comment by ddufresne** [comment]
@pnajman-modoolar Ok, thank you very much

**Comment by ddufresne** [comment]
@pnajman-modoolar any new on the version 11.0 ?

Can I help somehow ? testing, reviewing ?

**Comment by pnajman-modoolar** [comment]
@ddufresne We have just released version 11.0 and updated version 10.0

**Comment by ddufresne** [comment]
@pnajman-modoolar fantastic! thank you

**Comment by pnajman-modoolar** [comment]
Hi guys, we've released beta v11 and proposed it to https://github.com/OCA/ where its currently under code review. Our focus from now on will be on v11 only. Please check it out here and let us know what your needs are. Thanks.
